# Generated by Django 5.2 on 2025-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
